config/routes.rb
Rails.application.routes.draw do
  root    'static_pages#home'
  get     'signup', to: 'users#new'
  get     'signin',  to: 'sessions#new'
  post    'signin',  to: 'sessions#create'
  delete  'signout', to: 'sessions#destroy'
  resources :users
  resources :password_resets, only: [:new, :create, :edit, :update]
  resource  :dashboard,       only: [:show]
  resources :documents do
    resources :versions
  end

end

app/models/document.rb
class Document < ActiveRecord::Base
  belongs_to :category
  has_many :versions, dependent: :destroy
  belongs_to :current_version, class_name: "Version",
    foreign_key: "current_version_id", dependent: :destroy
  enum origin: %w(interno externo)

  validates :code,
            :title,
            :description,
            :origin,
            :location, presence: true
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update, :destroy]

  def index
    @documents = Document.all
  end

  def show
  end

  def new
    @document = Document.new
    @document.build_category
    @document.build_current_version
  end

  def edit
  end

  def create
    @document = Document.new(document_params)
    version = Version.new(uploaded_file:params[:uploaded_file])
    version.assign_number_last_version
    @document.current_version = version
    if @document.save
      redirect_to @document,
      notice: 'Document was successfully created.'
    else
      render :new
    end
  end

  def update
    if @document.update(document_params)
      redirect_to @document,
      notice: 'Document was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @document.destroy
      redirect_to documents_url,
      notice: 'Document was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params
      params.require(:document).permit(:code, :version, :origin, :title,
                                       :description, :location, :category_id)
    end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.erb
<%= form_for @document, :html => {:multipart => true} do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="row">
    <div class="col-sm-6">
      <div class="form-group">
        <%= f.label :code, "Codigo" %><br>
        <%= f.text_field :code, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :title, "Titulo" %><br>
        <%= f.text_field :title, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :description, "Descripción" %><br>
        <%= f.text_area(:description, size: '19x5', class: "form-control") %>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="form-group">
        <%= f.label :origin, "Origen" %><br>
        <%= f.select :origin, Document.origins.to_a.map { |o,| [o.humanize, o] }, {prompt: "Seleciona un origen"}, { class: 'form-control' } %>
      </div>
      <div class="form-group">
        <%= f.label :category_id, "Categoria" %><br>
        <%= f.collection_select(:category_id, Category.all, :id, :name, {prompt: "Selecciona una categoria"}, {class: "form-control"}) %>
      </div>
      <div class="form-group">
        <%= label_tag :uploaded_file, "Archivo" %><br>
        <%= file_field_tag :uploaded_file, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :location, "Ubicación" %><br>
        <%= f.text_field :location, class: "form-control" %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6 col-md-offset-6">
      <div class="actions text-right">
        <%= link_to "Cancelar", documents_path, class: "btn btn-default" %>
        <%= f.submit class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/documents/edit.html.erb
<% provide(:title, "Editar documento") %>
<div class="col-sm-10 col-sm-offset-1">
  <h1>Editar Documento</h1>

  <%= render 'form' %>
</div>

app/views/documents/index.html.erb
<% provide(:title, "Listado Maestro") %>
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="panel-title">
      <div class="row">
        <div class="col-sm-8">
          <h3>Listado Maestro</h3>
        </div>
        <div class="col-sm-4 text-right">
          <%= link_to 'New Document', new_document_path, class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
  <div class="panel-body">
    <div class="table-responsive">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Codigo</th>
            <th>Titulo</th>
            <th>Descripción</th>
            <th>Origen</th>
            <th>Categoria</th>
            <th>Ubicacion</th>
            <th>Version</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @documents.each do |document| %>
            <tr>
              <td><%= document.code %></td>
              <td><%= document.title %></td>
              <td><%= document.description %></td>
              <td><%= document.origin %></td>
              <td><%= document.category.name %></td>
              <td><%= document.location %></td>
              <td><%= document.current_version.number %></td>
              <td><%= link_to "Descargar", document.current_version.uploaded_file.url %></td>
              <td><%= link_to 'Show', document %></td>
              <td><%= link_to 'Edit', edit_document_path(document) %></td>
              <td><%= link_to 'Destroy', document, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

</div>

<br>

app/views/documents/new.html.erb
<% provide(:title, "Crear documento") %>
<div class="col-sm-10 col-sm-offset-1">
  <h1>Crear Documento</h1>

  <%= render 'form' %>
</div>

app/views/documents/show.html.erb
<% provide(:title, @document.title) %>
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="panel-title">
      <div class="row">
        <div class="col-sm-11 text-center">
          <h3><%= @document.title %></h3>
          <span>Titulo</span>
        </div>
        <div class="col-sm-1 text-center">
          <h3><%= @document.current_version.number %></h3>
          <span >Version</span>
        </div>
      </div>
    </div>
  </div>
  <div class="panel-body">
    <div class="table-responsive">
      <table class="table">
        <thead>
          <tr>
            <th>Codigo</th>
            <th>Descripción</th>
            <th>Origen</th>
            <th>Categoria</th>
            <th>Ubicación</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <tr>
            <td><%= @document.code %></td>
            <td><%= @document.description %></td>
            <td><%= @document.origin %></td>
            <td><%= @document.category.name %></td>
            <td><%= @document.location %></td>
            <td><%= link_to "Descargar", @document.current_version.uploaded_file.url %></td>
            <td></td>
            <td></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-sm-6">
    <div class="actions">
      <%= link_to 'Volver al Listado Maestro', documents_path, class: "btn btn-default" %>
    </div>
  </div>
</div>