config/routes.rb
Rails.application.routes.draw do
  root    'static_pages#home'
  get     'signup', to: 'users#new'
  get     'signin',  to: 'sessions#new'
  post    'signin',  to: 'sessions#create'
  delete  'signout', to: 'sessions#destroy'
  resources :users
  resources :password_resets, only: [:new, :create, :edit, :update]
  resource  :dashboard,       only: [:show]
  resources :documents do
    resources :versions
  end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <strong>SG Cloud</strong> Tu Sistema de Gestion en la Nube.
  </small>
  <nav>
    <ul>
      <li><%= link_to "Home",  root_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-default">
  <div class="container">
    <%= link_to "SG Cloud", root_path, class: "navbar-brand", id: "logo" %>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if signed_in? %>
          <li><%= link_to "Dashboard", dashboard_path %></li>
          <li><%= link_to "Usuarios", users_path %></li>
          <li><%= link_to "Crear Usuario", signup_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" >
              <%= current_user.first_name %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Perfil", current_user %></li>
              <li><%= link_to "Editar Perfil", edit_user_path(current_user) %></li>
              <li><%= link_to "Cambiar Contraseña", edit_password_reset_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= link_to "Salir", signout_path, method: "delete" %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Ingresar", signin_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE>
<html>
  <head>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
    <title>
      <%= full_title(yield(:title)) %>
    </title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim'%>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
    </div>
    <div class="container">
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>